(** Live-strict walker gate for corpus goal [lia_eq_from_bounds].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* x <= 5, 5 <= x |- x = 5 (antisymmetry; probes la_disequality/la_totality) *)
Theorem corpus_live_lia_eq_from_bounds :
  forall x : Z, x <= 5 -> 5 <= x -> x = 5.
Proof. intros x h1 h2. proof_broker_walker. Qed.

Print corpus_live_lia_eq_from_bounds.
Print Assumptions corpus_live_lia_eq_from_bounds.
