(** Live-strict walker gate for corpus goal [nat_eq_from_bounds].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* x+1 <= y, y <= 5, 6 <= x+w, w <= 2 |- x = 4 over ℕ (equality conclusion; the negated goal is a disjunction the walker case-handles — walker-live shape; the term-mode Nat.le_antisymm split is gated by the pb_nat_term_eq bridge tests) *)
Theorem corpus_live_nat_eq_from_bounds :
  forall x y w : nat, (x + 1 <= y)%nat -> (y <= 5)%nat -> (6 <= x + w)%nat -> (w <= 2)%nat -> x = 4%nat.
Proof. intros x y w h1 h2 h3 h4. proof_broker_walker. Qed.

Print corpus_live_nat_eq_from_bounds.
Print Assumptions corpus_live_nat_eq_from_bounds.
