(** Live-strict walker gate for corpus goal [nat_pow_bound].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* x < 2^16 |- x <= 65535 over ℕ (2^16-scale literal via reifier pow folding; R3-M1 gate shape. Scale is capped at 2^16 on purpose: the Rocq lift discharges plain ℕ decimal-literal leaves by kernel conversion, which normalizes the unary nat (2^24 measured at 7.4GB RSS / ~150s per coqc; see delta §5.4)) *)
Theorem corpus_live_nat_pow_bound :
  forall x : nat, (x < 2^16)%nat -> (x <= 65535)%nat.
Proof. intros x h. proof_broker_walker. Qed.

Print corpus_live_nat_pow_bound.
Print Assumptions corpus_live_nat_pow_bound.
