(** Live-strict walker gate for corpus goal [prop_excluded_middle].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* |- p \/ ~p (excluded middle; probes tautology/or rules) *)
Theorem corpus_live_prop_excluded_middle :
  forall p : Prop, p \/ ~p.
Proof. intros p. proof_broker_walker. Qed.

Print corpus_live_prop_excluded_middle.
Print Assumptions corpus_live_prop_excluded_middle.
