(** Live-strict walker gate for corpus goal [nat_d1_bracket].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* x < 2^24, z < 2*zmax, zmax*zhigh <= zmax |- x + z < 2^24 + 2*zmax over ℕ (the R4 D1 lift_cell shape: nonlinear atom zmax*zhigh atomized to an Opaque payload; forces Opaque into M1) *)
Theorem corpus_live_nat_d1_bracket :
  forall x z zmax zhigh : nat, (x < 2^24)%nat -> (z < 2 * zmax)%nat -> (zmax * zhigh <= zmax)%nat -> (x + z < 2^24 + 2 * zmax)%nat.
Proof. intros x z zmax zhigh hx hz hprod. proof_broker_walker. Qed.

Print corpus_live_nat_d1_bracket.
Print Assumptions corpus_live_nat_d1_bracket.
