(** Live-strict walker gate for corpus goal [lia_strict_trans].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* x < y, y < z |- x < z (strict transitivity; probes la_generic/comp_simplify) *)
Theorem corpus_live_lia_strict_trans :
  forall x y z : Z, x < y -> y < z -> x < z.
Proof. intros x y z h1 h2. proof_broker_walker. Qed.

Print corpus_live_lia_strict_trans.
Print Assumptions corpus_live_lia_strict_trans.
