(** Live-strict walker gate for corpus goal [uf_exists_witness].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* f y = 0 |- exists x, f x = 0 (existential from a witness; quantifier-rule discovery goal) *)
Theorem corpus_live_uf_exists_witness :
  forall (f : Z -> Z) (y : Z), f y = 0 -> exists x : Z, f x = 0.
Proof. intros f y h1. proof_broker_walker. Qed.

Print corpus_live_uf_exists_witness.
Print Assumptions corpus_live_uf_exists_witness.
