(** Live-strict walker gate for corpus goal [nat_strict_trans].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* a < b, b < c |- a < c over ℕ (strict chain; the ℕ image uses the +1 trick end-to-end) *)
Theorem corpus_live_nat_strict_trans :
  forall a b c : nat, (a < b)%nat -> (b < c)%nat -> (a < c)%nat.
Proof. intros a b c h1 h2. proof_broker_walker. Qed.

Print corpus_live_nat_strict_trans.
Print Assumptions corpus_live_nat_strict_trans.
