(** Live-strict walker gate for corpus goal [nat_sum_bound].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* x+1 <= y, y <= 5 |- x <= 4 over ℕ (the R3-M1 baseline: cast shells, nonneg hyps, primitive Nat metadata; term-mode AND walker shapes) *)
Theorem corpus_live_nat_sum_bound :
  forall x y : nat, (x + 1 <= y)%nat -> (y <= 5)%nat -> (x <= 4)%nat.
Proof. intros x y h1 h2. proof_broker_walker. Qed.

Print corpus_live_nat_sum_bound.
Print Assumptions corpus_live_nat_sum_bound.
