(** Dynamic replay gate for the walker over the cvc5 LIA+UF corpus.

    GENERATED by tools/gen_corpus_replay.py from corpus/goals + corpus/traces
    -- do not edit by hand. One theorem per statically-walkable corpus goal;
    each is proved by [alethe_walker_test] walking the verbatim cvc5
    alethe-2024 trace, with NO [lia] fallback. Compiling this file is the
    ground-truth check that every trace the static coverage report calls
    walkable actually closes under the Coq kernel. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* n + m = 10, 0 <= m |- n <= 10 (pure LIA; the snapshot shape) *)
Theorem corpus_lia_sum_bound :
  forall (n m : Z), n + m = 10 -> 0 <= m -> n <= 10.
Proof. intros n m h1 h3. alethe_walker_test "(
(assume a0 (! (= (+ n m) 10) :named @p_1))
(assume a1 (! (<= 0 m) :named @p_2))
(assume a2 (! (not (! (<= n 10) :named @p_3)) :named @p_4))
(step t0 (cl (not (! (= @p_4 (! (not (! (>= m 0) :named @p_5)) :named @p_7)) :named @p_8)) (not @p_4) @p_7) :rule equiv_pos2)
(step t1 (cl (! (= @p_3 (! (not (! (>= n 11) :named @p_9)) :named @p_15)) :named @p_18)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_18 3 7))
(step t2 (cl (= @p_4 (! (not @p_15) :named @p_16))) :rule cong :premises (t1))
(step t3 (cl (! (= @p_16 @p_9) :named @p_17)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_17 1 7))
(step t4 (cl (= @p_4 @p_9)) :rule trans :premises (t2 t3))
(step t5 (cl (not (! (= @p_1 (! (= n (! (+ 10 (* -1 m)) :named @p_10)) :named @p_13)) :named @p_14)) (not @p_1) @p_13) :rule equiv_pos2)
(step t6 (cl @p_14) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_14 3 7))
(step t7 (cl @p_13) :rule resolution :premises (t5 t6 a0))
(step t8 (cl (= 11 11)) :rule refl)
(step t9 (cl (= @p_9 (! (>= @p_10 11) :named @p_11))) :rule cong :premises (t7 t8))
(step t10 (cl (! (= @p_11 @p_7) :named @p_12)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_12 3 7))
(step t11 (cl (= @p_9 @p_7)) :rule trans :premises (t9 t10))
(step t12 (cl @p_8) :rule trans :premises (t4 t11))
(step t13 (cl @p_7) :rule resolution :premises (t0 t12 a2))
(step t14 (cl (not (! (= @p_2 @p_5) :named @p_6)) (not @p_2) @p_5) :rule equiv_pos2)
(step t15 (cl @p_6) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_6 3 7))
(step t16 (cl @p_5) :rule resolution :premises (t14 t15 a1))
(step t17 (cl) :rule resolution :premises (t13 t16))
)". Qed.

(* SKIPPED corpus_lia_weaken_bound: statically walkable but replay_skip: walker shape-gap: cvc5's equiv_simplify here uses a pattern beyond the 4 the elaborator handles ((= (= t t) true) / (= (not (not a)) a) / (= (and a a) a) / (= (or a a) a)). Statically walkable (all rules dispatched); dynamic gap tracked as coverage backlog. *)

(* a = b |- f a = f b (uninterpreted-function congruence) *)
Theorem corpus_uf_cong :
  forall (f : Z -> Z) (a b : Z), a = b -> f a = f b.
Proof. intros f a b h1. alethe_walker_test "(
(assume a0 (! (= a b) :named @p_1))
(assume a1 (! (not (! (= (f a) (! (f b) :named @p_2)) :named @p_3)) :named @p_4))
(step t0 (cl (not (! (= @p_4 false) :named @p_5)) (not @p_4) false) :rule equiv_pos2)
(step t1 (cl @p_3) :rule cong :premises (a0))
(step t2 (cl (! (= @p_2 @p_2) :named @p_6)) :rule refl)
(step t3 (cl (= @p_3 @p_6)) :rule cong :premises (t1 t2))
(step t4 (cl (= @p_4 (! (not @p_6) :named @p_7))) :rule cong :premises (t3))
(step t5 (cl (! (= @p_6 true) :named @p_10)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_10 3 6))
(step t6 (cl (= @p_7 (! (not true) :named @p_8))) :rule cong :premises (t5))
(step t7 (cl (! (= @p_8 false) :named @p_9)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_9 1 7))
(step t8 (cl (= @p_7 false)) :rule trans :premises (t6 t7))
(step t9 (cl @p_5) :rule trans :premises (t4 t8))
(step t10 (cl false) :rule resolution :premises (t0 t9 a1))
(step t11 (cl (not false)) :rule false)
(step t12 (cl) :rule resolution :premises (t10 t11))
)". Qed.

(* a = b, b = c |- a = c (equality transitivity) *)
Theorem corpus_uf_trans :
  forall (a b c : Z), a = b -> b = c -> a = c.
Proof. intros a b c h1 h2. alethe_walker_test "(
(assume a0 (! (= a b) :named @p_1))
(assume a1 (! (= b c) :named @p_2))
(assume a2 (! (not (! (= a c) :named @p_3)) :named @p_4))
(step t0 (cl (not (! (= @p_4 false) :named @p_5)) (not @p_4) false) :rule equiv_pos2)
(step t1 (cl @p_3) :rule trans :premises (a0 a1))
(step t2 (cl (! (= c c) :named @p_6)) :rule refl)
(step t3 (cl (= @p_3 @p_6)) :rule cong :premises (t1 t2))
(step t4 (cl (= @p_4 (! (not @p_6) :named @p_7))) :rule cong :premises (t3))
(step t5 (cl (! (= @p_6 true) :named @p_10)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_10 3 6))
(step t6 (cl (= @p_7 (! (not true) :named @p_8))) :rule cong :premises (t5))
(step t7 (cl (! (= @p_8 false) :named @p_9)) :rule hole :args (""TRUST_THEORY_REWRITE"" @p_9 1 7))
(step t8 (cl (= @p_7 false)) :rule trans :premises (t6 t7))
(step t9 (cl @p_5) :rule trans :premises (t4 t8))
(step t10 (cl false) :rule resolution :premises (t0 t9 a2))
(step t11 (cl (not false)) :rule false)
(step t12 (cl) :rule resolution :premises (t10 t11))
)". Qed.
