(** Live-strict walker gate for corpus goal [uf_forall_inst].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* (forall x, f x <= 10) |- f 3 <= 10 (universal instantiation; quantifier-rule discovery goal) *)
Theorem corpus_live_uf_forall_inst :
  forall (f : Z -> Z), (forall x : Z, f x <= 10) -> f 3 <= 10.
Proof. intros f h1. proof_broker_walker. Qed.

Print corpus_live_uf_forall_inst.
Print Assumptions corpus_live_uf_forall_inst.
