(** Live-strict walker gate for corpus goal [lia_pigeonhole3].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.

(* three values in {1,2} cannot be pairwise distinct (pigeonhole; large LIA+Boolean trace -- the corpus scale point, 636 steps / 118 arithmetic leaves) *)
Theorem corpus_live_lia_pigeonhole3 :
  forall a b c : Z, 1 <= a -> a <= 2 -> 1 <= b -> b <= 2 -> 1 <= c -> c <= 2 -> a <> b -> b <> c -> a <> c -> False.
Proof. intros a b c la ua lb ub lc uc dab dbc dac. proof_broker_walker. Qed.

Print corpus_live_lia_pigeonhole3.
Print Assumptions corpus_live_lia_pigeonhole3.
