#!/usr/bin/env python3
"""Generate the corpus walker gates: CorpusReplay.v + the live-strict suite.

Three generated surfaces, all derived from corpus/goals + corpus/traces:

1. rocq-bridge/theories/CorpusReplay.v — the HAND-FED replay gate. For
   every statically walkable corpus goal, emit

       Theorem corpus_<id> : <coq_goal>.
       Proof. alethe_walker_test "<verbatim cvc5 trace>". Qed.

   [alethe_walker_test] runs the walker ALONE on the committed trace — no
   [lia] fallback, no live solver — so a [Qed] proves the walker
   reconstructs cvc5's trace into a kernel proof of the goal.

2. rocq-bridge/theories/CorpusWalkerLive_<id>.v (one file per goal) — the
   LIVE-strict gate (R1.5). Each theorem closes with

       Proof. intros …. proof_broker_walker. Qed.

   which runs the full production path — reify, dispatch cvc5 live, mint
   a Tier-3 alethe-2024 cert through the SDK gate, walk it into a kernel
   term — with NO fallback closer. Each goal gets its OWN .v file because
   the axiom gate needs the [Print <name>.] marker + [Print Assumptions]
   block in the build log, and dune truncates per-action output head+tail:
   one big walker term (pigeonhole) in a shared file would evict its
   siblings' blocks from the trust gate (the TestSnapshot.v lesson).

3. lean-bridge/Test/CorpusWalkerLive.lean — the Lean live-strict twin.
   One generated lib (lakefile: ProofBrokerCorpusLive), one theorem per
   goal closing [by intro …; proof_broker_walker], plus a [#print axioms]
   line per theorem for the trust gate. Lake replays cached messages, so
   a single file is safe on the Lean side.

Goal statements come from the goal files' hand-authored [coq_goal] /
[lean_goal] fields; a goal missing [lean_goal] fails generation (fail
closed — the live suite must cover the whole corpus on BOTH bridges).

Generated, not hand-edited. Regenerate after refreshing the corpus:
    python tools/gen_corpus_replay.py --write
CI runs --check to fail if any committed output is stale w.r.t. the
fixtures (including a stale CorpusWalkerLive_*.v for a removed goal).
"""
from __future__ import annotations

import sys
from pathlib import Path

import check_walker_coverage as cov

ROOT = Path(__file__).resolve().parent.parent
GOALS = ROOT / "corpus" / "goals"
TRACES = ROOT / "corpus" / "traces"
OUT = ROOT / "rocq-bridge" / "theories" / "CorpusReplay.v"
ROCQ_LIVE_DIR = ROOT / "rocq-bridge" / "theories"
LEAN_OUT = ROOT / "lean-bridge" / "Test" / "CorpusWalkerLive.lean"

PREAMBLE = """\
(** Dynamic replay gate for the walker over the cvc5 LIA+UF corpus.

    GENERATED by tools/gen_corpus_replay.py from corpus/goals + corpus/traces
    -- do not edit by hand. One theorem per statically-walkable corpus goal;
    each is proved by [alethe_walker_test] walking the verbatim cvc5
    alethe-2024 trace, with NO [lia] fallback. Compiling this file is the
    ground-truth check that every trace the static coverage report calls
    walkable actually closes under the Coq kernel. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.
"""

ROCQ_LIVE_PREAMBLE = """\
(** Live-strict walker gate for corpus goal [{gid}].

    GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
    edit by hand. The theorem closes ONLY via [proof_broker_walker]: the
    full production path (reify -> live cvc5 dispatch -> SDK Tier-3 mint
    gate -> Alethe walker -> kernel), with NO [lia] fallback. One goal
    per file so each [Print]/[Print Assumptions] pair survives dune's
    per-action output truncation for the trust gate. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.
"""

LEAN_PREAMBLE = """\
/-
Live-strict walker suite over the cvc5 LIA+UF corpus (R1.5).

GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
edit by hand. One theorem per corpus goal, each closed ONLY via
`proof_broker_walker`: the full production path (reify the Lean goal,
dispatch cvc5 live, mint a Tier-3 alethe-2024 cert through the SDK
gate, walk the trace into a kernel proof term), with NO `omega`
fallback. Build success of this library is the gate; the `#print
axioms` line per theorem feeds the trust-footprint gate
(tools/check_axioms.py). Regenerate with
`python tools/gen_corpus_replay.py --write`.

Pre-condition: build with cwd = `lean-bridge/` (manifest discovery)
and the solvers on PATH — same as Test/Tactic.lean.
-/

import ProofBroker

set_option linter.unusedVariables false

namespace ProofBroker.TestCorpusLive
"""


def coq_escape(trace: str) -> str:
    """Escape a string for a Coq string literal: double every quote."""
    return trace.replace('"', '""')


def _goals_meta() -> dict:
    import json
    goals_meta = {}
    for f in sorted(GOALS.glob("*.json")):
        g = json.loads(f.read_text(encoding="utf-8"))
        goals_meta[g["id"]] = g
    return goals_meta


def _intro_names(meta: dict) -> list:
    """Binders to introduce, in goal order: the universally-quantified
    free vars, then the hypotheses — mirroring TestSnapshot.v's
    `intros n m h1 h3` so trace/goal atoms resolve against local
    hypotheses on both bridges."""
    ctx = meta["ir"]["context"]
    return ([fv["name"] for fv in ctx.get("free_vars", [])]
            + [h["name"] for h in ctx.get("hypotheses", [])])


def render() -> str:
    """The hand-fed CorpusReplay.v (unchanged surface)."""
    report = cov.compute()
    goals_meta = _goals_meta()

    blocks = [PREAMBLE]
    walkable = [gid for gid in sorted(report["goals"])
                if report["goals"][gid]["walkable"]]
    for gid in walkable:
        meta = goals_meta[gid]
        # A goal may be statically walkable (all rules dispatched) yet hit an
        # unhandled SHAPE of a supported rule under coqc. Such a goal carries
        # "replay_skip": "<reason>" in its goal file: excluded from the build
        # gate but still counted walkable by the static report. The mismatch
        # is the harness honestly recording a walker gap, not hiding it.
        skip = meta.get("replay_skip")
        if skip:
            blocks.append(
                f"\n(* SKIPPED corpus_{gid}: statically walkable but "
                f"replay_skip: {skip} *)\n")
            continue
        trace = (TRACES / f"{gid}.alethe").read_text(encoding="utf-8").strip()
        intro_names = _intro_names(meta)
        intros = f"intros {' '.join(intro_names)}. " if intro_names else ""
        blocks.append(
            f"\n(* {meta.get('description', gid)} *)\n"
            f"Theorem corpus_{gid} :\n  {meta['coq_goal']}.\n"
            f'Proof. {intros}alethe_walker_test "{coq_escape(trace)}". Qed.\n'
        )
    return "".join(blocks)


def live_goal_ids() -> list:
    """Goals in the live-strict suite: every mintable corpus goal
    without a replay_skip. The R1 gate expects this to be ALL of
    them — a shrink here is a reviewed diff, not a silent skip."""
    report = cov.compute()
    goals_meta = _goals_meta()
    return [gid for gid in sorted(report["goals"])
            if report["goals"][gid]["mintable"]
            and not goals_meta[gid].get("replay_skip")]


def render_rocq_live() -> dict:
    """Map of basename -> content for CorpusWalkerLive_<id>.v files."""
    goals_meta = _goals_meta()
    out = {}
    for gid in live_goal_ids():
        meta = goals_meta[gid]
        intro_names = _intro_names(meta)
        intros = f"intros {' '.join(intro_names)}. " if intro_names else ""
        name = f"corpus_live_{gid}"
        out[f"CorpusWalkerLive_{gid}.v"] = (
            ROCQ_LIVE_PREAMBLE.format(gid=gid)
            + f"\n(* {meta.get('description', gid)} *)\n"
            f"Theorem {name} :\n  {meta['coq_goal']}.\n"
            f"Proof. {intros}proof_broker_walker. Qed.\n"
            f"\nPrint {name}.\n"
            f"Print Assumptions {name}.\n"
        )
    return out


def render_lean_live() -> str:
    """The generated Test/CorpusWalkerLive.lean."""
    goals_meta = _goals_meta()
    blocks = [LEAN_PREAMBLE]
    for gid in live_goal_ids():
        meta = goals_meta[gid]
        lean_goal = meta.get("lean_goal")
        if not lean_goal:
            sys.exit(f"FAIL: corpus goal {gid} has no lean_goal field; "
                     f"the live suite must cover both bridges")
        intro_names = _intro_names(meta)
        intro = (f"  intro {' '.join(intro_names)}\n"
                 if intro_names else "")
        name = f"corpus_live_{gid}"
        blocks.append(
            f"\n/-- {meta.get('description', gid)} -/\n"
            f"theorem {name} : {lean_goal} := by\n"
            f"{intro}"
            f"  proof_broker_walker\n"
            f"\n#print axioms {name}\n"
        )
    blocks.append("\nend ProofBroker.TestCorpusLive\n")
    return "".join(blocks)


def _expected_outputs() -> dict:
    """Map of absolute Path -> expected content for every output."""
    out = {OUT: render(), LEAN_OUT: render_lean_live()}
    for base, content in render_rocq_live().items():
        out[ROCQ_LIVE_DIR / base] = content
    return out


def _stale_live_files(expected: dict) -> list:
    """Committed CorpusWalkerLive_*.v files no current goal produces."""
    have = set(ROCQ_LIVE_DIR.glob("CorpusWalkerLive_*.v"))
    want = {p for p in expected if p.name.startswith("CorpusWalkerLive_")}
    return sorted(have - want)


def main(argv: list) -> int:
    mode = argv[1] if len(argv) > 1 else ""
    expected = _expected_outputs()

    if mode == "--write":
        for path, text in expected.items():
            path.write_text(text, encoding="utf-8")
            n = sum(1 for ln in text.splitlines()
                    if ln.startswith(("Theorem ", "theorem ")))
            print(f"wrote {path.relative_to(ROOT)} ({n} theorems)")
        for p in _stale_live_files(expected):
            p.unlink()
            print(f"removed stale {p.relative_to(ROOT)}")
        return 0

    if mode == "--check":
        bad = []
        for path, text in expected.items():
            if not path.exists():
                bad.append(f"missing {path.relative_to(ROOT)}")
            elif path.read_text(encoding="utf-8") != text:
                bad.append(f"stale {path.relative_to(ROOT)}")
        for p in _stale_live_files(expected):
            bad.append(f"orphaned {p.relative_to(ROOT)} (no such goal)")
        if bad:
            for b in bad:
                print(f"FAIL: {b}")
            print("Regenerate: python tools/gen_corpus_replay.py --write")
            return 1
        print(f"OK: {len(expected)} generated corpus-gate files match the "
              f"fixtures ({len(expected) - 2} live Rocq goals + "
              f"CorpusReplay.v + CorpusWalkerLive.lean).")
        return 0

    sys.stdout.write(render())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
