#!/usr/bin/env python3
"""Generate the dynamic replay theory CorpusReplay.v from the corpus.

For every STATICALLY WALKABLE corpus goal (see check_walker_coverage), emit

    Theorem corpus_<id> : <coq_goal>.
    Proof. alethe_walker_test "<verbatim cvc5 trace>". Qed.

[alethe_walker_test] runs the walker ALONE -- no [lia] fallback -- so a [Qed]
succeeds only if the walker reconstructs cvc5's trace into a kernel proof of
the goal. Compiling this file under coqc in CI is therefore the DYNAMIC
ground-truth check behind the static coverage report: a goal the static
layer calls walkable but the walker cannot actually close fails the build,
exposing the discrepancy (a walker bug or an unhandled shape of a supported
rule).

We deliberately emit NO [Print]/[Print Assumptions]: this gate measures
walkability, not the trust footprint (that is covered by Test.v /
TestSnapshot.v). Omitting [Print] also keeps each goal's coqc output small,
sidestepping dune's per-action output truncation.

Generated, not hand-edited. Regenerate after refreshing the corpus:
    python tools/gen_corpus_replay.py --write
CI runs --check to fail if the committed .v is stale w.r.t. the fixtures.
"""
from __future__ import annotations

import sys
from pathlib import Path

import check_walker_coverage as cov

ROOT = Path(__file__).resolve().parent.parent
GOALS = ROOT / "corpus" / "goals"
TRACES = ROOT / "corpus" / "traces"
OUT = ROOT / "rocq-bridge" / "theories" / "CorpusReplay.v"

PREAMBLE = """\
(** Dynamic replay gate for the walker over the cvc5 LIA+UF corpus.

    GENERATED by tools/gen_corpus_replay.py from corpus/goals + corpus/traces
    -- do not edit by hand. One theorem per statically-walkable corpus goal;
    each is proved by [alethe_walker_test] walking the verbatim cvc5
    alethe-2024 trace, with NO [lia] fallback. Compiling this file is the
    ground-truth check that every trace the static coverage report calls
    walkable actually closes under the Coq kernel. Regenerate with
    [python tools/gen_corpus_replay.py --write]. *)

From Stdlib Require Import ZArith Lia.
From Stdlib Require Import Classical_Prop PropExtensionality.
From ProofBroker Require Import ProofBrokerTermMode.

Declare ML Module "proof_broker_rocq.plugin".

Open Scope Z_scope.
"""


def coq_escape(trace: str) -> str:
    """Escape a string for a Coq string literal: double every quote."""
    return trace.replace('"', '""')


def render() -> str:
    report = cov.compute()
    import json
    goals_meta = {}
    for f in sorted(GOALS.glob("*.json")):
        g = json.loads(f.read_text(encoding="utf-8"))
        goals_meta[g["id"]] = g

    blocks = [PREAMBLE]
    walkable = [gid for gid in sorted(report["goals"])
                if report["goals"][gid]["walkable"]]
    for gid in walkable:
        meta = goals_meta[gid]
        # A goal may be statically walkable (all rules dispatched) yet hit an
        # unhandled SHAPE of a supported rule under coqc. Such a goal carries
        # "replay_skip": "<reason>" in its goal file: excluded from the build
        # gate but still counted walkable by the static report. The mismatch
        # is the harness honestly recording a walker gap, not hiding it.
        skip = meta.get("replay_skip")
        if skip:
            blocks.append(
                f"\n(* SKIPPED corpus_{gid}: statically walkable but "
                f"replay_skip: {skip} *)\n")
            continue
        trace = (TRACES / f"{gid}.alethe").read_text(encoding="utf-8").strip()
        blocks.append(
            f"\n(* {meta.get('description', gid)} *)\n"
            f"Theorem corpus_{gid} :\n  {meta['coq_goal']}.\n"
            f'Proof. alethe_walker_test "{coq_escape(trace)}". Qed.\n'
        )
    return "".join(blocks)


def main(argv: list) -> int:
    mode = argv[1] if len(argv) > 1 else ""
    text = render()

    if mode == "--write":
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} "
              f"({text.count('Theorem ')} walkable theorems)")
        return 0

    if mode == "--check":
        if not OUT.exists():
            print(f"FAIL: {OUT} missing; run gen_corpus_replay.py --write")
            return 1
        if OUT.read_text(encoding="utf-8") == text:
            print(f"OK: {OUT.name} matches corpus "
                  f"({text.count('Theorem ')} theorems).")
            return 0
        print(f"FAIL: {OUT.name} is stale w.r.t. corpus fixtures. "
              f"Regenerate: python tools/gen_corpus_replay.py --write")
        return 1

    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
