#!/usr/bin/env python3
"""Script-derived project status table (the README "Status" section).

Every count the README shows about the shipped system is printed by
THIS script from the committed machine-readable sources listed below
— never typed by hand. The retrospectives record that hand-written
counts (allowlist size, axiom count, rule count, "16/16") went stale
within weeks of being written, so the README carries no numbers of
its own: it embeds the table between two marker comments and the
schemas CI job runs `--check` to keep the embedded copy identical to
what the sources say.

Sources (all committed, all already gated elsewhere in CI):
  tools/axiom_allowlist.json           trust gate: allowlisted theorems per
                                       bridge and the distinct axioms they
                                       may depend on (check_axioms.py)
  lean-bridge/ProofBroker/Alethe.lean  walker rule set, Lean side
  rocq-bridge/src/alethe_walker.ml     walker rule set, Rocq side
                                       (both via check_walker_parity.extract_rules)
  corpus/index.json                    corpus goals + proof steps (corpus_gen)
  corpus/coverage.json                 static replay coverage baseline
                                       (check_walker_coverage.py --check);
                                       `mintable` once R1 adds it
  examples/manifest-*.json             adapter manifests: backend + version
  .github/workflows/validate.yml       CI job list + timeout-minutes, and
                                       the solver/toolchain pins (env vars)
  lean-bridge/lean-toolchain           Lean toolchain pin
  proof_broker_rocq.opam               dune / rocq-runtime version bounds
  RETROSPECTIVES/*.md                  retrospective list

Modes:
  (default)  print the markdown table to stdout.
  --check    regenerate and compare with the block embedded in README.md
             between the markers; exit 1 with a diff on any difference
             (or if the markers are missing).
  --write    rewrite the README.md block in place.

Pure stdlib (validate.yml is parsed with regexes, not PyYAML, so the
schemas job needs no extra dependency). What this script deliberately
does NOT do: read any build output or run any tool — every number here
is a property of the committed tree, so the table is reproducible from
a checkout alone.
"""
from __future__ import annotations

import difflib
import json
import re
import sys
from pathlib import Path

import check_walker_parity as parity

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
ALLOWLIST = ROOT / "tools" / "axiom_allowlist.json"
INDEX = ROOT / "corpus" / "index.json"
COVERAGE = ROOT / "corpus" / "coverage.json"
WORKFLOW = ROOT / ".github" / "workflows" / "validate.yml"
LEAN_TOOLCHAIN = ROOT / "lean-bridge" / "lean-toolchain"
ROCQ_OPAM = ROOT / "proof_broker_rocq.opam"
MANIFESTS = sorted((ROOT / "examples").glob("manifest-*.json"))
RETROS = ROOT / "RETROSPECTIVES"

BEGIN = "<!-- status-table:begin (generated by tools/status_table.py; do not edit by hand) -->"
END = "<!-- status-table:end -->"


# ---------------------------------------------------------------- sources

def trust_gate(allowlist: dict) -> dict:
    """Per bridge: number of allowlisted theorems and the sorted set of
    distinct axioms any of them may depend on."""
    out = {}
    for bridge in ("lean", "rocq"):
        entries = allowlist[bridge]
        axioms: set = set()
        for axs in entries.values():
            axioms.update(axs)
        out[bridge] = {"theorems": len(entries), "axioms": sorted(axioms)}
    return out


def walker_rules() -> dict:
    lean = parity.extract_rules(parity.LEAN)
    rocq = parity.extract_rules(parity.ROCQ)
    return {"lean": len(lean), "rocq": len(rocq), "parity": lean == rocq}


def corpus(index: dict, coverage: dict) -> dict:
    s = coverage["summary"]
    return {
        "goals": len(index),
        "steps": sum(g["steps"] for g in index.values()),
        "walkable": s["walkable"],
        "replayed": s["replayed"],
        "total": s["total"],
        "supported_rule_count": coverage["supported_rule_count"],
        # R1.4 adds a `mintable` count (traces whose rule set is within
        # the SDK's Tier-3 mint gate). Until then it is reported as
        # unmeasured rather than assumed.
        "mintable": coverage.get("mintable"),
    }


def backends() -> list:
    out = []
    for m in MANIFESTS:
        d = json.loads(m.read_text(encoding="utf-8"))
        name = m.stem.removeprefix("manifest-")
        out.append((name, str(d.get("adapter_version", "?")),
                    d.get("tiers_produced", []),
                    d.get("trace_formats_produced") or []))
    return out


_JOB_HEADER = re.compile(r"^  ([A-Za-z0-9_-]+):\s*$")
_TIMEOUT = re.compile(r"^    timeout-minutes:\s*(\d+)\s*$")
_ENV_PIN = re.compile(r'^\s+(CVC5_VERSION|VAMPIRE_VERSION|ELAN_VERSION):\s*"([^"]+)"')
_OCAML = re.compile(r'^\s+ocaml-compiler:\s*"([^"]+)"')
_CRON = re.compile(r'^\s+- cron:\s*"([^"]+)"')


def ci_jobs(text: str) -> dict:
    """Job name -> timeout-minutes (None if absent), in file order, plus
    the solver/toolchain pins declared as env vars and the cron line.
    Regex-based: a job is a two-space-indented `name:` line after the
    `jobs:` line; its timeout is the four-space-indented
    `timeout-minutes:` line before the next job header."""
    jobs: dict = {}
    pins: dict = {}
    cron = None
    in_jobs = False
    current = None
    for line in text.splitlines():
        if line.strip() == "jobs:":
            in_jobs = True
            continue
        m = _CRON.match(line)
        if m:
            cron = m.group(1)
        m = _ENV_PIN.match(line)
        if m:
            pins.setdefault(m.group(1), set()).add(m.group(2))
        m = _OCAML.match(line)
        if m:
            pins.setdefault("ocaml-compiler", set()).add(m.group(1))
        if not in_jobs:
            continue
        m = _JOB_HEADER.match(line)
        if m:
            current = m.group(1)
            jobs[current] = None
            continue
        m = _TIMEOUT.match(line)
        if m and current is not None:
            jobs[current] = int(m.group(1))
    if not jobs:
        sys.exit(f"FAIL: no jobs found in {WORKFLOW}")
    return {"jobs": jobs, "pins": {k: sorted(v) for k, v in pins.items()},
            "cron": cron}


_OPAM_DEP = re.compile(r'^\s*"(dune|rocq-runtime)"\s*\{([^}]*)\}')


def version_bounds(opam_text: str) -> dict:
    out = {}
    for line in opam_text.splitlines():
        m = _OPAM_DEP.match(line)
        if m:
            out[m.group(1)] = m.group(2).replace('"', "").strip()
    return out


def retros() -> list:
    return sorted(p.name for p in RETROS.glob("*.md"))


# ---------------------------------------------------------------- render

def collect() -> dict:
    allowlist = json.loads(ALLOWLIST.read_text(encoding="utf-8"))
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    coverage = json.loads(COVERAGE.read_text(encoding="utf-8"))
    return {
        "trust": trust_gate(allowlist),
        "walker": walker_rules(),
        "corpus": corpus(index, coverage),
        "backends": backends(),
        "ci": ci_jobs(WORKFLOW.read_text(encoding="utf-8")),
        "bounds": version_bounds(ROCQ_OPAM.read_text(encoding="utf-8")),
        "lean": LEAN_TOOLCHAIN.read_text(encoding="utf-8").strip(),
        "retros": retros(),
    }


def _code(items) -> str:
    return ", ".join(f"`{x}`" for x in items)


def render(d: dict) -> str:
    t, w, c, ci = d["trust"], d["walker"], d["corpus"], d["ci"]
    rows = []

    def row(surface: str, value: str, source: str) -> None:
        rows.append(f"| {surface} | {value} | {source} |")

    for bridge, label in (("lean", "Lean"), ("rocq", "Rocq")):
        tb = t[bridge]
        row(f"Trust gate ({label})",
            f"{tb['theorems']} allowlisted theorems; "
            f"{len(tb['axioms'])} distinct axioms: {_code(tb['axioms'])}",
            "`tools/axiom_allowlist.json` (gated by `check_axioms.py` in "
            f"the {'lean' if bridge == 'lean' else 'rocq'}-bridge job)")

    par = "at parity" if w["parity"] else "**OUT OF PARITY**"
    row("Alethe walker rules",
        f"Lean {w['lean']}, Rocq {w['rocq']} ({par})",
        "dispatch arms between `PARITY:walker-rules` markers "
        "(`check_walker_parity.py`)")

    mint = (f"{c['mintable']}/{c['total']}" if c["mintable"] is not None
            else "not measured — `coverage.json` has no `mintable` key yet (R1)")
    row("Walker corpus",
        f"{c['goals']} goals, {c['steps']} proof steps; statically walkable "
        f"{c['walkable']}/{c['total']}; in the generated `CorpusReplay.v` "
        f"{c['replayed']}/{c['total']} (the coqc ground truth is that file "
        "compiling in the rocq-bridge job); live-mintable "
        f"{mint}",
        "`corpus/index.json`, `corpus/coverage.json` "
        "(`check_walker_coverage.py --check`, `gen_corpus_replay.py --check`)")

    be = "; ".join(
        f"{name} {ver} (tiers {','.join(map(str, tiers))}"
        + (f"; {','.join(fmts)}" if fmts else "") + ")"
        for name, ver, tiers, fmts in d["backends"])
    row("Backends (adapter manifests)", be, "`examples/manifest-*.json`")

    pins = ci["pins"]

    def pin(k: str) -> str:
        return "/".join(pins.get(k, ["?"]))

    row("Toolchain pins",
        f"Lean `{d['lean']}`; OCaml `{pin('ocaml-compiler')}`; "
        f"dune `{d['bounds'].get('dune', '?')}`; "
        f"rocq-runtime `{d['bounds'].get('rocq-runtime', '?')}`; "
        f"cvc5 `{pin('CVC5_VERSION')}`; Vampire `{pin('VAMPIRE_VERSION')}`; "
        f"elan `{pin('ELAN_VERSION')}`",
        "`lean-bridge/lean-toolchain`, `proof_broker_rocq.opam`, "
        "`validate.yml` env pins")

    jobs = "; ".join(
        f"{name}" + (f" ({to} min)" if to is not None else " (no timeout)")
        for name, to in ci["jobs"].items())
    cron = f"weekly cron `{ci['cron']}`" if ci["cron"] else "no cron"
    row("CI jobs (timeout)", f"{jobs}; {cron}", "`.github/workflows/validate.yml`")

    row("Retrospectives", _code(d["retros"]), "`RETROSPECTIVES/`")

    header = ["| surface | value | source |", "|---|---|---|"]
    return "\n".join(header + rows) + "\n"


def block(table: str) -> str:
    return f"{BEGIN}\n{table}{END}"


# ---------------------------------------------------------------- README I/O

def readme_split(text: str):
    """(before, embedded_block, after) or None if the markers are absent."""
    try:
        before, rest = text.split(BEGIN, 1)
        inner, after = rest.split(END, 1)
    except ValueError:
        return None
    return before, BEGIN + inner + END, after


def check(readme_text: str, table: str) -> int:
    parts = readme_split(readme_text)
    if parts is None:
        print(f"FAIL: {README.name} has no status-table markers "
              f"({BEGIN!r} … {END!r}); run `tools/status_table.py --write`.")
        return 1
    embedded = parts[1]
    expected = block(table)
    if embedded == expected:
        print(f"OK: {README.name} status table matches the sources.")
        return 0
    print(f"FAIL: {README.name} status table is stale; run "
          "`python3 tools/status_table.py --write` and commit the diff:")
    for line in difflib.unified_diff(embedded.splitlines(), expected.splitlines(),
                                     "README (embedded)", "generated", lineterm=""):
        print(line)
    return 1


def write(readme_text: str, table: str) -> str:
    parts = readme_split(readme_text)
    if parts is None:
        sys.exit(f"FAIL: {README.name} has no status-table markers; add "
                 f"{BEGIN!r} and {END!r} where the table belongs.")
    before, _, after = parts
    return before + block(table) + after


def main(argv: list) -> int:
    table = render(collect())
    if "--check" in argv:
        return check(README.read_text(encoding="utf-8"), table)
    if "--write" in argv:
        README.write_text(write(README.read_text(encoding="utf-8"), table),
                          encoding="utf-8")
        print(f"wrote {README.relative_to(ROOT)}")
        return 0
    sys.stdout.write(table)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
