/-
Live-strict walker suite over the cvc5 LIA+UF corpus (R1.5).

GENERATED by tools/gen_corpus_replay.py from corpus/goals -- do not
edit by hand. One theorem per corpus goal, each closed ONLY via
`proof_broker_walker`: the full production path (reify the Lean goal,
dispatch cvc5 live, mint a Tier-3 alethe-2024 cert through the SDK
gate, walk the trace into a kernel proof term), with NO `omega`
fallback. Build success of this library is the gate; the `#print
axioms` line per theorem feeds the trust-footprint gate
(tools/check_axioms.py). Regenerate with
`python tools/gen_corpus_replay.py --write`.

Pre-condition: build with cwd = `lean-bridge/` (manifest discovery)
and the solvers on PATH — same as Test/Tactic.lean.
-/

import ProofBroker

set_option linter.unusedVariables false

namespace ProofBroker.TestCorpusLive

/-- |- x <= 0 \/ 1 <= x (integer trichotomy; probes boolean/case rules) -/
theorem corpus_live_lia_disjunction : ∀ x : Int, x ≤ 0 ∨ 1 ≤ x := by
  intro x
  proof_broker_walker

#print axioms corpus_live_lia_disjunction

/-- x <= 5, 5 <= x |- x = 5 (antisymmetry; probes la_disequality/la_totality) -/
theorem corpus_live_lia_eq_from_bounds : ∀ x : Int, x ≤ 5 → 5 ≤ x → x = 5 := by
  intro x h1 h2
  proof_broker_walker

#print axioms corpus_live_lia_eq_from_bounds

/-- x <= 3, 5 <= x |- False (False-conclusion goal: exercises the (not false) negated-goal assume) -/
theorem corpus_live_lia_false_from_bounds : ∀ x : Int, x ≤ 3 → 5 ≤ x → False := by
  intro x h1 h2
  proof_broker_walker

#print axioms corpus_live_lia_false_from_bounds

/-- |- ~(x < x) (irreflexivity of <; probes comp_simplify/la_generic + not) -/
theorem corpus_live_lia_irrefl : ∀ x : Int, ¬(x < x) := by
  intro x
  proof_broker_walker

#print axioms corpus_live_lia_irrefl

/-- three values in {1,2} cannot be pairwise distinct (pigeonhole; large LIA+Boolean trace -- the corpus scale point, 636 steps / 118 arithmetic leaves) -/
theorem corpus_live_lia_pigeonhole3 : ∀ a b c : Int, 1 ≤ a → a ≤ 2 → 1 ≤ b → b ≤ 2 → 1 ≤ c → c ≤ 2 → a ≠ b → b ≠ c → a ≠ c → False := by
  intro a b c la ua lb ub lc uc dab dbc dac
  proof_broker_walker

#print axioms corpus_live_lia_pigeonhole3

/-- x < y, y < z |- x < z (strict transitivity; probes la_generic/comp_simplify) -/
theorem corpus_live_lia_strict_trans : ∀ x y z : Int, x < y → y < z → x < z := by
  intro x y z h1 h2
  proof_broker_walker

#print axioms corpus_live_lia_strict_trans

/-- n + m = 10, 0 <= m |- n <= 10 (pure LIA; the snapshot shape) -/
theorem corpus_live_lia_sum_bound : ∀ n m : Int, n + m = 10 → 0 ≤ m → n ≤ 10 := by
  intro n m h1 h3
  proof_broker_walker

#print axioms corpus_live_lia_sum_bound

/-- 3 <= x |- 1 <= x (single-step LIA weakening) -/
theorem corpus_live_lia_weaken_bound : ∀ x : Int, 3 ≤ x → 1 ≤ x := by
  intro x h1
  proof_broker_walker

#print axioms corpus_live_lia_weaken_bound

/-- ~(p \/ q) |- ~p /\ ~q (de Morgan; probes not_or/and rules/and_simplify) -/
theorem corpus_live_prop_demorgan : ∀ p q : Prop, ¬(p ∨ q) → ¬p ∧ ¬q := by
  intro p q h1
  proof_broker_walker

#print axioms corpus_live_prop_demorgan

/-- p = q, q = r |- p = r (Prop-equality transitivity; Bool-= reifies as @eq Prop, exercising the propext path) -/
theorem corpus_live_prop_eq_trans : ∀ p q r : Prop, p = q → q = r → p = r := by
  intro p q r h1 h2
  proof_broker_walker

#print axioms corpus_live_prop_eq_trans

/-- |- p \/ ~p (excluded middle; probes tautology/or rules) -/
theorem corpus_live_prop_excluded_middle : ∀ p : Prop, p ∨ ¬p := by
  intro p
  proof_broker_walker

#print axioms corpus_live_prop_excluded_middle

/-- a = b |- f a = f b (uninterpreted-function congruence) -/
theorem corpus_live_uf_cong : ∀ (f : Int → Int) (a b : Int), a = b → f a = f b := by
  intro f a b h1
  proof_broker_walker

#print axioms corpus_live_uf_cong

/-- f y = 0 |- exists x, f x = 0 (existential from a witness; quantifier-rule discovery goal) -/
theorem corpus_live_uf_exists_witness : ∀ (f : Int → Int) (y : Int), f y = 0 → ∃ x : Int, f x = 0 := by
  intro f y h1
  proof_broker_walker

#print axioms corpus_live_uf_exists_witness

/-- (forall x, f x <= 10) |- f 3 <= 10 (universal instantiation; quantifier-rule discovery goal) -/
theorem corpus_live_uf_forall_inst : ∀ (f : Int → Int), (∀ x : Int, f x ≤ 10) → f 3 ≤ 10 := by
  intro f h1
  proof_broker_walker

#print axioms corpus_live_uf_forall_inst

/-- f x = x, 0 <= x |- 0 <= f x (mixed UF + LIA) -/
theorem corpus_live_uf_lia_mix : ∀ (f : Int → Int) (x : Int), f x = x → 0 ≤ x → 0 ≤ f x := by
  intro f x h1 h2
  proof_broker_walker

#print axioms corpus_live_uf_lia_mix

/-- f c <= T, T < f (c - 1) |- f c < f (c - 1) (threshold-bracket core: UF applied to a difference, the verinf threshold_unique shape; R4 regression, added R1.7) -/
theorem corpus_live_uf_lia_threshold : ∀ (f : Int → Int) (c T : Int), f c ≤ T → T < f (c - 1) → f c < f (c - 1) := by
  intro f c T h1 h2
  proof_broker_walker

#print axioms corpus_live_uf_lia_threshold

/-- a = b, b = c |- a = c (equality transitivity) -/
theorem corpus_live_uf_trans : ∀ a b c : Int, a = b → b = c → a = c := by
  intro a b c h1 h2
  proof_broker_walker

#print axioms corpus_live_uf_trans

end ProofBroker.TestCorpusLive
